// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemcSys.Data;

#nullable disable

namespace RemcSys.Migrations.RemcDB
{
    [DbContext(typeof(RemcDBContext))]
    partial class RemcDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RemcSys.Models.ActionLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FraType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjLead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.HasIndex("FraId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("RemcSys.Models.Evaluation", b =>
                {
                    b.Property<string>("evaluation_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("assigned_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("evaluation_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("evaluation_Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("evaluation_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("evaluator_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("evaluator_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fra_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("evaluation_Id");

                    b.HasIndex("fra_Id");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("RemcSys.Models.FileRequirement", b =>
                {
                    b.Property<string>("fr_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("file_Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("file_Uploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("fra_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("fr_Id");

                    b.HasIndex("fra_Id");

                    b.ToTable("FileRequirement");
                });

            modelBuilder.Entity("RemcSys.Models.FundedResearchApplication", b =>
                {
                    b.Property<string>("fra_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("applicant_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("applicant_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("application_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("college")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dts_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("field_of_Study")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fra_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("research_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("submission_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("team_Members")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fra_Id");

                    b.ToTable("FundedResearchApplication");
                });

            modelBuilder.Entity("RemcSys.Models.FundedResearchEthics", b =>
                {
                    b.Property<string>("fre_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("completionCertificate_Id")
                        .HasColumnType("int");

                    b.Property<int?>("ethicClearance_Id")
                        .HasColumnType("int");

                    b.Property<string>("fra_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("urec_No")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fre_Id");

                    b.HasIndex("fra_Id")
                        .IsUnique();

                    b.ToTable("FundedResearchEthics");
                });

            modelBuilder.Entity("RemcSys.Models.GeneratedForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("fra_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("fra_Id");

                    b.ToTable("GeneratedForms");
                });

            modelBuilder.Entity("RemcSys.Models.ActionLog", b =>
                {
                    b.HasOne("RemcSys.Models.FundedResearchApplication", "fundedResearchApplication")
                        .WithMany("ActionLogs")
                        .HasForeignKey("FraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fundedResearchApplication");
                });

            modelBuilder.Entity("RemcSys.Models.Evaluation", b =>
                {
                    b.HasOne("RemcSys.Models.FundedResearchApplication", "fundedResearchApplication")
                        .WithMany("Evaluations")
                        .HasForeignKey("fra_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fundedResearchApplication");
                });

            modelBuilder.Entity("RemcSys.Models.FileRequirement", b =>
                {
                    b.HasOne("RemcSys.Models.FundedResearchApplication", "fundedResearchApplication")
                        .WithMany("FileRequirements")
                        .HasForeignKey("fra_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fundedResearchApplication");
                });

            modelBuilder.Entity("RemcSys.Models.FundedResearchEthics", b =>
                {
                    b.HasOne("RemcSys.Models.FundedResearchApplication", "FundedResearchApplication")
                        .WithOne("FundedResearchEthics")
                        .HasForeignKey("RemcSys.Models.FundedResearchEthics", "fra_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundedResearchApplication");
                });

            modelBuilder.Entity("RemcSys.Models.GeneratedForm", b =>
                {
                    b.HasOne("RemcSys.Models.FundedResearchApplication", "FundedResearchApplication")
                        .WithMany("GeneratedForms")
                        .HasForeignKey("fra_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundedResearchApplication");
                });

            modelBuilder.Entity("RemcSys.Models.FundedResearchApplication", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("Evaluations");

                    b.Navigation("FileRequirements");

                    b.Navigation("FundedResearchEthics")
                        .IsRequired();

                    b.Navigation("GeneratedForms");
                });
#pragma warning restore 612, 618
        }
    }
}
